name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello there, this is your first time doing a pull request or issue to this repository, Find bugs or submit a pull request to improve the code'
        pr-message: 'Find bugs for do pull request'
